apiVersion: v1
kind: ConfigMap
metadata:
  name: matter-server-verify-script
  namespace: matter-server
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/*").AsConfig | nindent 2 }}
